### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by AXKuhta** [librity/weekendrt#3]
- Consider hosting the images on imgur or maybe github release description? Having them in repo makes it take a while to clone on a 100 kb/s connection.
- Add -O2 to cflags; it reveals some warnings that -Werror treats as errors. Happens at least on gcc-10.

I used this raytracer to benchmark an overclock on an ARM board, and it picked it up nicely!

Thank you for this C adaptation.

**Comment by librity** [comment]
Those are all good ideas, I will implement them when I have more time.
